module Bank{
    
        domain Bank;
 
    subdomain Atm;



     provided interface IBank{
          inv:  balance() >= creditLimit() .
            
                   
    void deposit(in int ClientNum, in string Amount)
     
          {  pre: Amount > 0 .

             pre: validClient(ClientNum) == true .
                                         post: self.Amount = self.Amount + Amount .
     
          };

    void withdrawal(out int CardNo, in string Password, in int Amount)

          {  pre: self.Amount > Amount .
      
             pre: Password <> empty .
          
             pre: validCard(CardNo) == true .
 
             post: self.Amount = self.Amount - Amount .
                                         inv: length(Password) > 7 .
            
          };

          void createSession();
   
          void locateBank();
        
        };


    };