module Bank{
    domain       Bank;
    subdomain    Atm;

     provided interface IBank{      
           inv: balance() >= creditLimit() .   

           void createSession();
           void locateBank();
           void deposit(in int Amount, in int ClientNum)
           {   pre: amount > 0.
               pre: validClient(numclient) == true.    
               post: self.amount = self.amount + amount.          
           };
           void withdrawal(in int CardNo, in string Password, in int Amount)
           {   pre: self.amount > amount .
               pre: password <> empty .
               pre: validCard(cardno) == true .
               post: self.amount = self.amount + amount .
               inv: length(password) > 5 .
           };
      };
};